# Generated by Django 5.2.5 on 2025-08-17 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_patientprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentManagement",
            fields=[
                (
                    "appointment_id",
                    models.AutoField(
                        help_text="Unique identifier for the appointment.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(help_text="Date and time of the appointment."),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("follow_up", "Follow Up"),
                            ("emergency", "Emergency"),
                        ],
                        default="consultation",
                        max_length=50,
                    ),
                ),
                (
                    "appointment_time",
                    models.TimeField(help_text="Time of the appointment."),
                ),
                (
                    "queue_number",
                    models.PositiveIntegerField(
                        help_text="Queue number for the appointment.", unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="users.generaldoctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Management",
                "verbose_name_plural": "Appointment Management",
                "db_table": "appointment_management",
                "ordering": ["appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="Messaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Message content.")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the message was sent.",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaging",
                "verbose_name_plural": "Messaging",
                "db_table": "messaging",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Notification message.")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the notification has been read.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the notification was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the notification was last updated.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicineInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(help_text="Name of the medicine.", max_length=100),
                ),
                (
                    "stock_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Current stock of the medicine."
                    ),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Current available stock of the medicine."
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit of the medicine.",
                        max_digits=10,
                    ),
                ),
                (
                    "minimum_stock_level",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum stock level before reordering."
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Expiry date of the medicine.", null=True
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Batch number of the medicine.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "last_restocked",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time the medicine was restocked."
                    ),
                ),
                (
                    "usage_pattern",
                    models.TextField(
                        blank=True,
                        help_text="Description of the usage pattern for the medicine.",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        limit_choices_to={"user__role": "nurse"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_inventory",
                        to="users.nurseprofile",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medicine_inventory",
                        to="operations.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Inventory",
                "verbose_name_plural": "Medicine Inventory",
                "db_table": "medicine_inventory",
                "ordering": ["medicine_name"],
            },
        ),
        migrations.CreateModel(
            name="PriorityQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Priority level of the patient in the queue.",
                        max_length=50,
                    ),
                ),
                (
                    "actual_wait_time",
                    models.DurationField(
                        blank=True,
                        help_text="Actual wait time for the patient.",
                        null=True,
                    ),
                ),
                (
                    "estimated_wait_time",
                    models.DurationField(
                        blank=True,
                        help_text="Estimated wait time for the patient.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue_number",
                    models.PositiveIntegerField(
                        help_text="Queue number for the priority patient.", unique=True
                    ),
                ),
                (
                    "appointment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_queue",
                        to="operations.appointmentmanagement",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="priority_queue",
                        to="operations.notification",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_queue",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Queue",
                "verbose_name_plural": "Priority Queues",
                "db_table": "priority_queue",
                "ordering": ["-priority_level"],
            },
        ),
        migrations.CreateModel(
            name="QueueManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queue_number", models.PositiveIntegerField(unique=True)),
                (
                    "total_patients",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of patients in the queue."
                    ),
                ),
                (
                    "estimated_wait_time",
                    models.DurationField(
                        blank=True,
                        help_text="Estimated wait time for the patient.",
                        null=True,
                    ),
                ),
                (
                    "actual_wait_time",
                    models.DurationField(
                        blank=True,
                        help_text="Actual wait time for the patient.",
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("OPD", "Out Patient Department"),
                            ("Billing", "Billing"),
                            ("Pharmacy", "Pharmacy"),
                            ("Appointment", "Appointment"),
                        ],
                        help_text="Department for which the queue is managed.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_management",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Management",
                "verbose_name_plural": "Queue Management",
                "db_table": "queue_management",
                "ordering": ["queue_number"],
            },
        ),
    ]
