# Generated by Django 5.2.5 on 2025-09-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_priorityqueue_options_and_more'),
        ('users', '0005_nurseprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when doctor is unavailable')),
                ('reason', models.CharField(blank=True, help_text='Reason for unavailability', max_length=255)),
                ('is_blocked', models.BooleanField(default=True, help_text='Whether the date is blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.generaldoctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availability',
                'db_table': 'doctor_availability',
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
