# Generated by Django 5.2.5 on 2025-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemanagement',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the queue started.', null=True),
        ),
    ]
