# Generated by Django 4.2.7 on 2025-09-14 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0004_messaging_is_read_messaging_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Message content.")),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional file attachment",
                        null=True,
                        upload_to="message_attachments/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, help_text="Original file name", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been read"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the message was sent.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="operations.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="messaging",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Legacy Messaging",
                "verbose_name_plural": "Legacy Messaging",
            },
        ),
        migrations.RemoveField(
            model_name="messaging",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="messaging",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="messagereaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("love", "❤️"),
                    ("laugh", "😂"),
                    ("wow", "😮"),
                    ("sad", "😢"),
                    ("angry", "😠"),
                ],
                default="like",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="messaging",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="messaging",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MessageAttachment",
        ),
        migrations.AlterField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="operations.message",
            ),
        ),
    ]
