# Generated by Django 4.2.7 on 2025-09-27 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0005_conversation_message_alter_messaging_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, help_text="When the message was delivered", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="encrypted_content",
            field=models.TextField(
                blank=True, help_text="Base64 encoded encrypted content"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_delivered",
            field=models.BooleanField(
                default=False, help_text="Whether the message has been delivered"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(
                blank=True, help_text="When the message was read", null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(help_text="Encrypted message content."),
        ),
        migrations.CreateModel(
            name="MessageNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_message", "New Message"),
                            ("message_delivered", "Message Delivered"),
                            ("message_read", "Message Read"),
                        ],
                        default="new_message",
                        max_length=20,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="operations.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Notification",
                "verbose_name_plural": "Message Notifications",
                "db_table": "message_notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
