# Generated by Django 4.2.7 on 2025-09-27 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_patientprofile_admission_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0006_message_delivered_at_message_encrypted_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization_required",
                    models.CharField(
                        help_text="Required specialization for this assignment",
                        max_length=100,
                    ),
                ),
                (
                    "assignment_reason",
                    models.TextField(blank=True, help_text="Reason for assignment"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Assignment status",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the patient was assigned"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the doctor accepted the assignment",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the consultation was completed",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Assignment priority",
                        max_length=10,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Nurse who assigned the patient",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_patients",
                        to="users.generaldoctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Assignment",
                "verbose_name_plural": "Patient Assignments",
                "db_table": "patient_assignments",
                "ordering": ["-assigned_at"],
                "unique_together": {("patient", "doctor", "assigned_at")},
            },
        ),
        migrations.CreateModel(
            name="ConsultationNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(help_text="Patient's main complaint"),
                ),
                (
                    "history_of_present_illness",
                    models.TextField(
                        help_text="Detailed history of the current illness"
                    ),
                ),
                (
                    "physical_examination",
                    models.TextField(help_text="Physical examination findings"),
                ),
                ("diagnosis", models.TextField(help_text="Doctor's diagnosis")),
                (
                    "treatment_plan",
                    models.TextField(help_text="Recommended treatment plan"),
                ),
                (
                    "medications_prescribed",
                    models.TextField(blank=True, help_text="Medications prescribed"),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(
                        blank=True, help_text="Follow-up instructions for the patient"
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, help_text="Any additional notes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="draft",
                        help_text="Status of the consultation notes",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notes were created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the notes were last updated"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the consultation was completed",
                        null=True,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_notes",
                        to="operations.patientassignment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_notes",
                        to="users.generaldoctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_notes",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Notes",
                "verbose_name_plural": "Consultation Notes",
                "db_table": "consultation_notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
