# Generated by Django 5.2.5 on 2025-09-17 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=255, unique=True)),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analytics Cache",
                "verbose_name_plural": "Analytics Cache",
                "db_table": "analytics_cache",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("record_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("triggered_analytics", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Data Update Log",
                "verbose_name_plural": "Data Update Logs",
                "db_table": "data_update_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("patient_health_trends", "Patient Health Trends"),
                            ("patient_demographics", "Patient Demographics"),
                            ("illness_prediction", "Illness Prediction"),
                            ("medication_analysis", "Medication Analysis"),
                            ("patient_volume_prediction", "Patient Volume Prediction"),
                            ("illness_surge_prediction", "Illness Surge Prediction"),
                            ("full_analysis", "Full Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Result",
                "verbose_name_plural": "Analytics Results",
                "db_table": "analytics_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("patient_health_trends", "Patient Health Trends"),
                            ("patient_demographics", "Patient Demographics"),
                            ("illness_prediction", "Illness Prediction"),
                            ("medication_analysis", "Medication Analysis"),
                            ("patient_volume_prediction", "Patient Volume Prediction"),
                            ("illness_surge_prediction", "Illness Surge Prediction"),
                            ("full_analysis", "Full Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.analyticsresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Task",
                "verbose_name_plural": "Analytics Tasks",
                "db_table": "analytics_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
