# Generated by Django 4.2.7 on 2025-09-18 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_admission", models.DateTimeField()),
                ("medical_condition", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("medication", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                (
                    "treatment_outcome",
                    models.CharField(
                        choices=[
                            ("Recovered", "Recovered"),
                            ("Ongoing", "Ongoing"),
                            ("Transferred", "Transferred"),
                            ("Deceased", "Deceased"),
                        ],
                        default="Ongoing",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Record",
                "verbose_name_plural": "Patient Records",
                "db_table": "patient_records",
                "ordering": ["-date_of_admission"],
            },
        ),
    ]
