# Generated by Django 4.2.7 on 2025-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_patientrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="is_dummy_data",
            field=models.BooleanField(
                default=False, help_text="Mark as dummy data for testing"
            ),
        ),
    ]
