# Generated by Django 4.2.7 on 2025-09-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_patientrecord_is_dummy_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrecord",
            name="is_dummy_data",
        ),
        migrations.AlterField(
            model_name="analyticsresult",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("patient_health_trends", "Patient Health Trends"),
                    ("patient_demographics", "Patient Demographics"),
                    ("illness_prediction", "Illness Prediction"),
                    ("medication_analysis", "Medication Analysis"),
                    ("patient_volume_prediction", "Patient Volume Prediction"),
                    ("illness_surge_prediction", "Illness Surge Prediction"),
                    ("weekly_illness_forecast", "Weekly Illness Forecast"),
                    ("monthly_illness_forecast", "Monthly Illness Forecast"),
                    ("full_analysis", "Full Analysis"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analyticstask",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("patient_health_trends", "Patient Health Trends"),
                    ("patient_demographics", "Patient Demographics"),
                    ("illness_prediction", "Illness Prediction"),
                    ("medication_analysis", "Medication Analysis"),
                    ("patient_volume_prediction", "Patient Volume Prediction"),
                    ("illness_surge_prediction", "Illness Surge Prediction"),
                    ("weekly_illness_forecast", "Weekly Illness Forecast"),
                    ("monthly_illness_forecast", "Monthly Illness Forecast"),
                    ("full_analysis", "Full Analysis"),
                ],
                max_length=50,
            ),
        ),
    ]
