# Generated by Django 5.2.5 on 2025-08-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
