# Generated by Django 4.2.7 on 2025-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_site", "0002_alter_adminuser_managers_alter_adminuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
