# Generated by Django 5.2.5 on 2025-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="generaldoctorprofile",
            name="doctor_name",
        ),
        migrations.RemoveField(
            model_name="generaldoctorprofile",
            name="role",
        ),
        migrations.RemoveField(
            model_name="generaldoctorprofile",
            name="years_of_experience",
        ),
        migrations.RemoveField(
            model_name="nurseprofile",
            name="nurse_name",
        ),
        migrations.RemoveField(
            model_name="nurseprofile",
            name="role",
        ),
        migrations.AlterField(
            model_name="generaldoctorprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="nurseprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
