# Generated by Django 5.2.5 on 2025-08-17 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=3,
                    ),
                ),
                (
                    "medical_condition",
                    models.TextField(
                        blank=True,
                        help_text="A summary of the patient's current medical condition.",
                    ),
                ),
                ("date_of_admission", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                (
                    "medication",
                    models.TextField(
                        blank=True, help_text="List of prescribed medications."
                    ),
                ),
                (
                    "test_results",
                    models.TextField(
                        blank=True, help_text="Summary of recent test results."
                    ),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The primary doctor assigned to this patient.",
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
                "db_table": "patient_profiles",
            },
        ),
    ]
