# Generated by Django 5.2.5 on 2025-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_patientprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_document",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF, JPG, or PNG file for identity verification",
                null=True,
                upload_to="verification_documents/",
            ),
        ),
    ]
