# Generated by Django 5.2.5 on 2025-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_profile_picture_user_verification_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="nurseprofile",
            name="department",
            field=models.CharField(
                blank=True, help_text="Department where the nurse works", max_length=255
            ),
        ),
    ]
