# Generated by Django 4.2.7 on 2025-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_nurseprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Admin Review"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
    ]
