# Generated by Django 4.2.7 on 2025-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_verification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="admission_type",
            field=models.CharField(
                blank=True,
                help_text="Type of admission (emergency, scheduled, etc.).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="billing_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Billing amount for treatment.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="hospital",
            field=models.CharField(
                blank=True,
                help_text="Hospital or medical facility name.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="insurance_provider",
            field=models.CharField(
                blank=True, help_text="Patient's insurance provider.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="room_number",
            field=models.CharField(
                blank=True, help_text="Hospital room number.", max_length=20
            ),
        ),
    ]
